title: OnlyBuns
author: Smári bakari
description: A simple website about my friend.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
logo: smari.jpeg  # Updated to match your image filename
